// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var com = com || {};

/**
 * @const
 * @namespace
 */
com.reactivemarkets = com.reactivemarkets || {};

/**
 * @const
 * @namespace
 */
com.reactivemarkets.papi = com.reactivemarkets.papi || {};

/**
 * @enum {number}
 */
com.reactivemarkets.papi.FeedType = {
  Default: 0,
  Trade: 1
};

/**
 * @enum {string}
 */
com.reactivemarkets.papi.FeedTypeName = {
  '0': 'Default',
  '1': 'Trade'
};

/**
 * @enum {number}
 */
com.reactivemarkets.papi.Side = {
  Sell: -1,
  None: 0,
  Buy: 1
};

/**
 * @enum {string}
 */
com.reactivemarkets.papi.SideName = {
  '-1': 'Sell',
  '0': 'None',
  '1': 'Buy'
};

/**
 * @enum {number}
 */
com.reactivemarkets.papi.SubReqType = {
  Subscribe: 1,
  Unsubscribe: 2
};

/**
 * @enum {string}
 */
com.reactivemarkets.papi.SubReqTypeName = {
  '1': 'Subscribe',
  '2': 'Unsubscribe'
};

// Exports for Node.js and RequireJS
this.com = com;
