// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var com = com || {};

/**
 * @const
 * @namespace
 */
com.reactivemarkets = com.reactivemarkets || {};

/**
 * @const
 * @namespace
 */
com.reactivemarkets.papi = com.reactivemarkets.papi || {};

/**
 * @constructor
 */
com.reactivemarkets.papi.FeedRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.reactivemarkets.papi.FeedRequest}
 */
com.reactivemarkets.papi.FeedRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.reactivemarkets.papi.FeedRequest=} obj
 * @returns {com.reactivemarkets.papi.FeedRequest}
 */
com.reactivemarkets.papi.FeedRequest.getRootAsFeedRequest = function(bb, obj) {
  return (obj || new com.reactivemarkets.papi.FeedRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.reactivemarkets.papi.FeedRequest=} obj
 * @returns {com.reactivemarkets.papi.FeedRequest}
 */
com.reactivemarkets.papi.FeedRequest.getSizePrefixedRootAsFeedRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new com.reactivemarkets.papi.FeedRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.reactivemarkets.papi.FeedRequest.prototype.reqId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {com.reactivemarkets.papi.SubReqType}
 */
com.reactivemarkets.papi.FeedRequest.prototype.subReqType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {com.reactivemarkets.papi.SubReqType} */ (this.bb.readInt16(this.bb_pos + offset)) : com.reactivemarkets.papi.SubReqType.Subscribe;
};

/**
 * @returns {com.reactivemarkets.papi.FeedType}
 */
com.reactivemarkets.papi.FeedRequest.prototype.feedType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {com.reactivemarkets.papi.FeedType} */ (this.bb.readInt16(this.bb_pos + offset)) : com.reactivemarkets.papi.FeedType.Default;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.FeedRequest.prototype.grouping = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.FeedRequest.prototype.depth = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.FeedRequest.prototype.frequency = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
com.reactivemarkets.papi.FeedRequest.prototype.markets = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.FeedRequest.prototype.marketsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.reactivemarkets.papi.FeedRequest.startFeedRequest = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reqIdOffset
 */
com.reactivemarkets.papi.FeedRequest.addReqId = function(builder, reqIdOffset) {
  builder.addFieldOffset(0, reqIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {com.reactivemarkets.papi.SubReqType} subReqType
 */
com.reactivemarkets.papi.FeedRequest.addSubReqType = function(builder, subReqType) {
  builder.addFieldInt16(1, subReqType, com.reactivemarkets.papi.SubReqType.Subscribe);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {com.reactivemarkets.papi.FeedType} feedType
 */
com.reactivemarkets.papi.FeedRequest.addFeedType = function(builder, feedType) {
  builder.addFieldInt16(2, feedType, com.reactivemarkets.papi.FeedType.Default);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} grouping
 */
com.reactivemarkets.papi.FeedRequest.addGrouping = function(builder, grouping) {
  builder.addFieldInt16(3, grouping, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} depth
 */
com.reactivemarkets.papi.FeedRequest.addDepth = function(builder, depth) {
  builder.addFieldInt16(4, depth, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} frequency
 */
com.reactivemarkets.papi.FeedRequest.addFrequency = function(builder, frequency) {
  builder.addFieldInt16(5, frequency, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} marketsOffset
 */
com.reactivemarkets.papi.FeedRequest.addMarkets = function(builder, marketsOffset) {
  builder.addFieldOffset(6, marketsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
com.reactivemarkets.papi.FeedRequest.createMarketsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
com.reactivemarkets.papi.FeedRequest.startMarketsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.reactivemarkets.papi.FeedRequest.endFeedRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reqIdOffset
 * @param {NS10566075735762053212.com.reactivemarkets.papi.SubReqType} subReqType
 * @param {NS10566075735762053212.com.reactivemarkets.papi.FeedType} feedType
 * @param {number} grouping
 * @param {number} depth
 * @param {number} frequency
 * @param {flatbuffers.Offset} marketsOffset
 * @returns {flatbuffers.Offset}
 */
com.reactivemarkets.papi.FeedRequest.createFeedRequest = function(builder, reqIdOffset, subReqType, feedType, grouping, depth, frequency, marketsOffset) {
  com.reactivemarkets.papi.FeedRequest.startFeedRequest(builder);
  com.reactivemarkets.papi.FeedRequest.addReqId(builder, reqIdOffset);
  com.reactivemarkets.papi.FeedRequest.addSubReqType(builder, subReqType);
  com.reactivemarkets.papi.FeedRequest.addFeedType(builder, feedType);
  com.reactivemarkets.papi.FeedRequest.addGrouping(builder, grouping);
  com.reactivemarkets.papi.FeedRequest.addDepth(builder, depth);
  com.reactivemarkets.papi.FeedRequest.addFrequency(builder, frequency);
  com.reactivemarkets.papi.FeedRequest.addMarkets(builder, marketsOffset);
  return com.reactivemarkets.papi.FeedRequest.endFeedRequest(builder);
}

// Exports for Node.js and RequireJS
this.com = com;
