// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var com = com || {};

/**
 * @const
 * @namespace
 */
com.reactivemarkets = com.reactivemarkets || {};

/**
 * @const
 * @namespace
 */
com.reactivemarkets.papi = com.reactivemarkets.papi || {};

/**
 * @constructor
 */
com.reactivemarkets.papi.MDLevel2 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.reactivemarkets.papi.MDLevel2}
 */
com.reactivemarkets.papi.MDLevel2.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDLevel2.prototype.qty = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDLevel2.prototype.price = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} qty
 * @param {number} price
 * @returns {flatbuffers.Offset}
 */
com.reactivemarkets.papi.MDLevel2.createMDLevel2 = function(builder, qty, price) {
  builder.prep(8, 16);
  builder.writeFloat64(price);
  builder.writeFloat64(qty);
  return builder.offset();
};

/**
 * @constructor
 */
com.reactivemarkets.papi.MDSnapshotL2 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.reactivemarkets.papi.MDSnapshotL2}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.reactivemarkets.papi.MDSnapshotL2=} obj
 * @returns {com.reactivemarkets.papi.MDSnapshotL2}
 */
com.reactivemarkets.papi.MDSnapshotL2.getRootAsMDSnapshotL2 = function(bb, obj) {
  return (obj || new com.reactivemarkets.papi.MDSnapshotL2).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.reactivemarkets.papi.MDSnapshotL2=} obj
 * @returns {com.reactivemarkets.papi.MDSnapshotL2}
 */
com.reactivemarkets.papi.MDSnapshotL2.getSizePrefixedRootAsMDSnapshotL2 = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new com.reactivemarkets.papi.MDSnapshotL2).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.sourceTs = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.source = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.market = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.feedId = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.depth = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.flags = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {com.reactivemarkets.papi.MDLevel2=} obj
 * @returns {com.reactivemarkets.papi.MDLevel2}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.bidSide = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? (obj || new com.reactivemarkets.papi.MDLevel2).__init(this.bb.__vector(this.bb_pos + offset) + index * 16, this.bb) : null;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.bidSideLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {com.reactivemarkets.papi.MDLevel2=} obj
 * @returns {com.reactivemarkets.papi.MDLevel2}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.offerSide = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? (obj || new com.reactivemarkets.papi.MDLevel2).__init(this.bb.__vector(this.bb_pos + offset) + index * 16, this.bb) : null;
};

/**
 * @returns {number}
 */
com.reactivemarkets.papi.MDSnapshotL2.prototype.offerSideLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.reactivemarkets.papi.MDSnapshotL2.startMDSnapshotL2 = function(builder) {
  builder.startObject(9);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} sourceTs
 */
com.reactivemarkets.papi.MDSnapshotL2.addSourceTs = function(builder, sourceTs) {
  builder.addFieldInt64(0, sourceTs, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sourceOffset
 */
com.reactivemarkets.papi.MDSnapshotL2.addSource = function(builder, sourceOffset) {
  builder.addFieldOffset(1, sourceOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} marketOffset
 */
com.reactivemarkets.papi.MDSnapshotL2.addMarket = function(builder, marketOffset) {
  builder.addFieldOffset(2, marketOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} feedId
 */
com.reactivemarkets.papi.MDSnapshotL2.addFeedId = function(builder, feedId) {
  builder.addFieldInt32(3, feedId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
com.reactivemarkets.papi.MDSnapshotL2.addId = function(builder, id) {
  builder.addFieldInt64(4, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} depth
 */
com.reactivemarkets.papi.MDSnapshotL2.addDepth = function(builder, depth) {
  builder.addFieldInt16(5, depth, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} flags
 */
com.reactivemarkets.papi.MDSnapshotL2.addFlags = function(builder, flags) {
  builder.addFieldInt16(6, flags, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bidSideOffset
 */
com.reactivemarkets.papi.MDSnapshotL2.addBidSide = function(builder, bidSideOffset) {
  builder.addFieldOffset(7, bidSideOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
com.reactivemarkets.papi.MDSnapshotL2.startBidSideVector = function(builder, numElems) {
  builder.startVector(16, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offerSideOffset
 */
com.reactivemarkets.papi.MDSnapshotL2.addOfferSide = function(builder, offerSideOffset) {
  builder.addFieldOffset(8, offerSideOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
com.reactivemarkets.papi.MDSnapshotL2.startOfferSideVector = function(builder, numElems) {
  builder.startVector(16, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.reactivemarkets.papi.MDSnapshotL2.endMDSnapshotL2 = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 8); // market
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} sourceTs
 * @param {flatbuffers.Offset} sourceOffset
 * @param {flatbuffers.Offset} marketOffset
 * @param {number} feedId
 * @param {flatbuffers.Long} id
 * @param {number} depth
 * @param {number} flags
 * @param {flatbuffers.Offset} bidSideOffset
 * @param {flatbuffers.Offset} offerSideOffset
 * @returns {flatbuffers.Offset}
 */
com.reactivemarkets.papi.MDSnapshotL2.createMDSnapshotL2 = function(builder, sourceTs, sourceOffset, marketOffset, feedId, id, depth, flags, bidSideOffset, offerSideOffset) {
  com.reactivemarkets.papi.MDSnapshotL2.startMDSnapshotL2(builder);
  com.reactivemarkets.papi.MDSnapshotL2.addSourceTs(builder, sourceTs);
  com.reactivemarkets.papi.MDSnapshotL2.addSource(builder, sourceOffset);
  com.reactivemarkets.papi.MDSnapshotL2.addMarket(builder, marketOffset);
  com.reactivemarkets.papi.MDSnapshotL2.addFeedId(builder, feedId);
  com.reactivemarkets.papi.MDSnapshotL2.addId(builder, id);
  com.reactivemarkets.papi.MDSnapshotL2.addDepth(builder, depth);
  com.reactivemarkets.papi.MDSnapshotL2.addFlags(builder, flags);
  com.reactivemarkets.papi.MDSnapshotL2.addBidSide(builder, bidSideOffset);
  com.reactivemarkets.papi.MDSnapshotL2.addOfferSide(builder, offerSideOffset);
  return com.reactivemarkets.papi.MDSnapshotL2.endMDSnapshotL2(builder);
}

// Exports for Node.js and RequireJS
this.com = com;
