// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUM_REACTIVEMARKETS_PAPI_H_
#define FLATBUFFERS_GENERATED_ENUM_REACTIVEMARKETS_PAPI_H_

#include "flatbuffers/flatbuffers.h"

namespace reactivemarkets {
namespace papi {

enum class FeedType : int16_t {
  Default = 0,
  Trade = 1,
  MIN = Default,
  MAX = Trade
};

inline const FeedType (&EnumValuesFeedType())[2] {
  static const FeedType values[] = {
    FeedType::Default,
    FeedType::Trade
  };
  return values;
}

inline const char * const *EnumNamesFeedType() {
  static const char * const names[3] = {
    "Default",
    "Trade",
    nullptr
  };
  return names;
}

inline const char *EnumNameFeedType(FeedType e) {
  if (flatbuffers::IsOutRange(e, FeedType::Default, FeedType::Trade)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFeedType()[index];
}

enum class Side : int8_t {
  Sell = -1,
  None = 0,
  Buy = 1,
  MIN = Sell,
  MAX = Buy
};

inline const Side (&EnumValuesSide())[3] {
  static const Side values[] = {
    Side::Sell,
    Side::None,
    Side::Buy
  };
  return values;
}

inline const char * const *EnumNamesSide() {
  static const char * const names[4] = {
    "Sell",
    "None",
    "Buy",
    nullptr
  };
  return names;
}

inline const char *EnumNameSide(Side e) {
  if (flatbuffers::IsOutRange(e, Side::Sell, Side::Buy)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(Side::Sell);
  return EnumNamesSide()[index];
}

enum class SubReqType : int8_t {
  Subscribe = 1,
  Unsubscribe = 2,
  MIN = Subscribe,
  MAX = Unsubscribe
};

inline const SubReqType (&EnumValuesSubReqType())[2] {
  static const SubReqType values[] = {
    SubReqType::Subscribe,
    SubReqType::Unsubscribe
  };
  return values;
}

inline const char * const *EnumNamesSubReqType() {
  static const char * const names[3] = {
    "Subscribe",
    "Unsubscribe",
    nullptr
  };
  return names;
}

inline const char *EnumNameSubReqType(SubReqType e) {
  if (flatbuffers::IsOutRange(e, SubReqType::Subscribe, SubReqType::Unsubscribe)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(SubReqType::Subscribe);
  return EnumNamesSubReqType()[index];
}

}  // namespace papi
}  // namespace reactivemarkets

#endif  // FLATBUFFERS_GENERATED_ENUM_REACTIVEMARKETS_PAPI_H_
