// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LIQUIDATIONORDER_REACTIVE_PAPI_H_
#define FLATBUFFERS_GENERATED_LIQUIDATIONORDER_REACTIVE_PAPI_H_

#include "flatbuffers/flatbuffers.h"

#include "Enum_generated.h"

namespace reactive {
namespace papi {

struct LiquidationOrder;
struct LiquidationOrderBuilder;

struct LiquidationOrder FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LiquidationOrderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_TS = 4,
    VT_SOURCE = 6,
    VT_MARKET = 8,
    VT_FEED_ID = 10,
    VT_ORDER_ID = 12,
    VT_FLAGS = 14,
    VT_SIDE = 16,
    VT_QTY = 18,
    VT_PRICE = 20
  };
  int64_t source_ts() const {
    return GetField<int64_t>(VT_SOURCE_TS, 0);
  }
  const flatbuffers::String *source() const {
    return GetPointer<const flatbuffers::String *>(VT_SOURCE);
  }
  const flatbuffers::String *market() const {
    return GetPointer<const flatbuffers::String *>(VT_MARKET);
  }
  int32_t feed_id() const {
    return GetField<int32_t>(VT_FEED_ID, 0);
  }
  const flatbuffers::String *order_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ORDER_ID);
  }
  uint16_t flags() const {
    return GetField<uint16_t>(VT_FLAGS, 0);
  }
  reactive::papi::Side side() const {
    return static_cast<reactive::papi::Side>(GetField<int8_t>(VT_SIDE, 0));
  }
  double qty() const {
    return GetField<double>(VT_QTY, 0.0);
  }
  double price() const {
    return GetField<double>(VT_PRICE, 0.0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_SOURCE_TS) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           VerifyOffsetRequired(verifier, VT_MARKET) &&
           verifier.VerifyString(market()) &&
           VerifyField<int32_t>(verifier, VT_FEED_ID) &&
           VerifyOffset(verifier, VT_ORDER_ID) &&
           verifier.VerifyString(order_id()) &&
           VerifyField<uint16_t>(verifier, VT_FLAGS) &&
           VerifyField<int8_t>(verifier, VT_SIDE) &&
           VerifyField<double>(verifier, VT_QTY) &&
           VerifyField<double>(verifier, VT_PRICE) &&
           verifier.EndTable();
  }
};

struct LiquidationOrderBuilder {
  typedef LiquidationOrder Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_source_ts(int64_t source_ts) {
    fbb_.AddElement<int64_t>(LiquidationOrder::VT_SOURCE_TS, source_ts, 0);
  }
  void add_source(flatbuffers::Offset<flatbuffers::String> source) {
    fbb_.AddOffset(LiquidationOrder::VT_SOURCE, source);
  }
  void add_market(flatbuffers::Offset<flatbuffers::String> market) {
    fbb_.AddOffset(LiquidationOrder::VT_MARKET, market);
  }
  void add_feed_id(int32_t feed_id) {
    fbb_.AddElement<int32_t>(LiquidationOrder::VT_FEED_ID, feed_id, 0);
  }
  void add_order_id(flatbuffers::Offset<flatbuffers::String> order_id) {
    fbb_.AddOffset(LiquidationOrder::VT_ORDER_ID, order_id);
  }
  void add_flags(uint16_t flags) {
    fbb_.AddElement<uint16_t>(LiquidationOrder::VT_FLAGS, flags, 0);
  }
  void add_side(reactive::papi::Side side) {
    fbb_.AddElement<int8_t>(LiquidationOrder::VT_SIDE, static_cast<int8_t>(side), 0);
  }
  void add_qty(double qty) {
    fbb_.AddElement<double>(LiquidationOrder::VT_QTY, qty, 0.0);
  }
  void add_price(double price) {
    fbb_.AddElement<double>(LiquidationOrder::VT_PRICE, price, 0.0);
  }
  explicit LiquidationOrderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<LiquidationOrder> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LiquidationOrder>(end);
    fbb_.Required(o, LiquidationOrder::VT_MARKET);
    return o;
  }
};

inline flatbuffers::Offset<LiquidationOrder> CreateLiquidationOrder(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t source_ts = 0,
    flatbuffers::Offset<flatbuffers::String> source = 0,
    flatbuffers::Offset<flatbuffers::String> market = 0,
    int32_t feed_id = 0,
    flatbuffers::Offset<flatbuffers::String> order_id = 0,
    uint16_t flags = 0,
    reactive::papi::Side side = reactive::papi::Side::None,
    double qty = 0.0,
    double price = 0.0) {
  LiquidationOrderBuilder builder_(_fbb);
  builder_.add_price(price);
  builder_.add_qty(qty);
  builder_.add_source_ts(source_ts);
  builder_.add_order_id(order_id);
  builder_.add_feed_id(feed_id);
  builder_.add_market(market);
  builder_.add_source(source);
  builder_.add_flags(flags);
  builder_.add_side(side);
  return builder_.Finish();
}

inline flatbuffers::Offset<LiquidationOrder> CreateLiquidationOrderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t source_ts = 0,
    const char *source = nullptr,
    const char *market = nullptr,
    int32_t feed_id = 0,
    const char *order_id = nullptr,
    uint16_t flags = 0,
    reactive::papi::Side side = reactive::papi::Side::None,
    double qty = 0.0,
    double price = 0.0) {
  auto source__ = source ? _fbb.CreateString(source) : 0;
  auto market__ = market ? _fbb.CreateString(market) : 0;
  auto order_id__ = order_id ? _fbb.CreateString(order_id) : 0;
  return reactive::papi::CreateLiquidationOrder(
      _fbb,
      source_ts,
      source__,
      market__,
      feed_id,
      order_id__,
      flags,
      side,
      qty,
      price);
}

}  // namespace papi
}  // namespace reactive

#endif  // FLATBUFFERS_GENERATED_LIQUIDATIONORDER_REACTIVE_PAPI_H_
