# automatically generated by the FlatBuffers compiler, do not modify

# namespace: papi

class Body(object):
    NONE = 0
    FeedRequest = 1
    FeedRequestAccept = 2
    FeedRequestReject = 3
    LiquidationOrder = 4
    MDSnapshotL2 = 5
    PublicTrade = 6
    SessionStatus = 7

