# automatically generated by the FlatBuffers compiler, do not modify

# namespace: papi

class Body(object):
    NONE = 0
    FeedRequest = 1
    FeedRequestAccept = 2
    FeedRequestReject = 3
    MDSnapshotL2 = 4
    PublicTrade = 5
    SessionStatus = 6

