# automatically generated by the FlatBuffers compiler, do not modify

# namespace: papi

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FeedRequestAccept(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFeedRequestAccept(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeedRequestAccept()
        x.Init(buf, n + offset)
        return x

    # FeedRequestAccept
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FeedRequestAccept
    def ReqId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FeedRequestAccept
    def FeedId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FeedRequestAcceptStart(builder): builder.StartObject(2)
def FeedRequestAcceptAddReqId(builder, reqId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(reqId), 0)
def FeedRequestAcceptAddFeedId(builder, feedId): builder.PrependInt32Slot(1, feedId, 0)
def FeedRequestAcceptEnd(builder): return builder.EndObject()
