// automatically generated by the FlatBuffers compiler, do not modify

import { flatbuffers } from "./flatbuffers"
/**
 * @constructor
 */
export namespace com.reactivemarkets.papi{
export class FeedRequestReject {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FeedRequestReject
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FeedRequestReject {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FeedRequestReject= obj
 * @returns FeedRequestReject
 */
static getRootAsFeedRequestReject(bb:flatbuffers.ByteBuffer, obj?:FeedRequestReject):FeedRequestReject {
  return (obj || new FeedRequestReject()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FeedRequestReject= obj
 * @returns FeedRequestReject
 */
static getSizePrefixedRootAsFeedRequestReject(bb:flatbuffers.ByteBuffer, obj?:FeedRequestReject):FeedRequestReject {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeedRequestReject()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
reqId():string|null
reqId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
reqId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
errorCode():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
errorMessage():string|null
errorMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
errorMessage(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFeedRequestReject(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset reqIdOffset
 */
static addReqId(builder:flatbuffers.Builder, reqIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, reqIdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number errorCode
 */
static addErrorCode(builder:flatbuffers.Builder, errorCode:number) {
  builder.addFieldInt32(1, errorCode, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset errorMessageOffset
 */
static addErrorMessage(builder:flatbuffers.Builder, errorMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorMessageOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFeedRequestReject(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFeedRequestReject(builder:flatbuffers.Builder, reqIdOffset:flatbuffers.Offset, errorCode:number, errorMessageOffset:flatbuffers.Offset):flatbuffers.Offset {
  FeedRequestReject.startFeedRequestReject(builder);
  FeedRequestReject.addReqId(builder, reqIdOffset);
  FeedRequestReject.addErrorCode(builder, errorCode);
  FeedRequestReject.addErrorMessage(builder, errorMessageOffset);
  return FeedRequestReject.endFeedRequestReject(builder);
}
}
}
