// automatically generated by the FlatBuffers compiler, do not modify

import * as NS6823633475464199631 from "./SessionStatus_generated";
export namespace PlatformApi { 
export import SessionStatus = NS6823633475464199631.PlatformApi.SessionStatus;
}
import * as NS584072177544900616 from "./PublicTrade_generated";
export namespace PlatformApi { 
export import PublicTrade = NS584072177544900616.PlatformApi.PublicTrade;
}
import * as NS13677774665957090232 from "./FeedRequest_generated";
export namespace PlatformApi { 
export import FeedRequest = NS13677774665957090232.PlatformApi.FeedRequest;
}
import * as NS4318123797752956812 from "./FeedRequestAccept_generated";
export namespace PlatformApi { 
export import FeedRequestAccept = NS4318123797752956812.PlatformApi.FeedRequestAccept;
}
import * as NS2618412122345160958 from "./MDSnapshotL2_generated";
export namespace PlatformApi { 
export import MDSnapshotL2 = NS2618412122345160958.PlatformApi.MDSnapshotL2;
}
import * as NS3180374600874012547 from "./FeedRequestReject_generated";
export namespace PlatformApi { 
export import FeedRequestReject = NS3180374600874012547.PlatformApi.FeedRequestReject;
}
/**
 * @enum {number}
 */
export namespace PlatformApi{
export enum Body{
  NONE= 0,
  FeedRequest= 1,
  FeedRequestAccept= 2,
  FeedRequestReject= 3,
  MDSnapshotL2= 4,
  PublicTrade= 5,
  SessionStatus= 6
};

export function unionToBody(
  type: Body,
  accessor: (obj:PlatformApi.FeedRequest|PlatformApi.FeedRequestAccept|PlatformApi.FeedRequestReject|PlatformApi.MDSnapshotL2|PlatformApi.PublicTrade|PlatformApi.SessionStatus) => PlatformApi.FeedRequest|PlatformApi.FeedRequestAccept|PlatformApi.FeedRequestReject|PlatformApi.MDSnapshotL2|PlatformApi.PublicTrade|PlatformApi.SessionStatus|null
): PlatformApi.FeedRequest|PlatformApi.FeedRequestAccept|PlatformApi.FeedRequestReject|PlatformApi.MDSnapshotL2|PlatformApi.PublicTrade|PlatformApi.SessionStatus|null {
  switch(PlatformApi.Body[type]) {
    case 'NONE': return null; 
    case 'FeedRequest': return accessor(new PlatformApi.FeedRequest())! as PlatformApi.FeedRequest;
    case 'FeedRequestAccept': return accessor(new PlatformApi.FeedRequestAccept())! as PlatformApi.FeedRequestAccept;
    case 'FeedRequestReject': return accessor(new PlatformApi.FeedRequestReject())! as PlatformApi.FeedRequestReject;
    case 'MDSnapshotL2': return accessor(new PlatformApi.MDSnapshotL2())! as PlatformApi.MDSnapshotL2;
    case 'PublicTrade': return accessor(new PlatformApi.PublicTrade())! as PlatformApi.PublicTrade;
    case 'SessionStatus': return accessor(new PlatformApi.SessionStatus())! as PlatformApi.SessionStatus;
    default: return null;
  }
}

export function unionListToBody(
  type: Body, 
  accessor: (index: number, obj:PlatformApi.FeedRequest|PlatformApi.FeedRequestAccept|PlatformApi.FeedRequestReject|PlatformApi.MDSnapshotL2|PlatformApi.PublicTrade|PlatformApi.SessionStatus) => PlatformApi.FeedRequest|PlatformApi.FeedRequestAccept|PlatformApi.FeedRequestReject|PlatformApi.MDSnapshotL2|PlatformApi.PublicTrade|PlatformApi.SessionStatus|null, 
  index: number
): PlatformApi.FeedRequest|PlatformApi.FeedRequestAccept|PlatformApi.FeedRequestReject|PlatformApi.MDSnapshotL2|PlatformApi.PublicTrade|PlatformApi.SessionStatus|null {
  switch(PlatformApi.Body[type]) {
    case 'NONE': return null; 
    case 'FeedRequest': return accessor(index, new PlatformApi.FeedRequest())! as PlatformApi.FeedRequest;
    case 'FeedRequestAccept': return accessor(index, new PlatformApi.FeedRequestAccept())! as PlatformApi.FeedRequestAccept;
    case 'FeedRequestReject': return accessor(index, new PlatformApi.FeedRequestReject())! as PlatformApi.FeedRequestReject;
    case 'MDSnapshotL2': return accessor(index, new PlatformApi.MDSnapshotL2())! as PlatformApi.MDSnapshotL2;
    case 'PublicTrade': return accessor(index, new PlatformApi.PublicTrade())! as PlatformApi.PublicTrade;
    case 'SessionStatus': return accessor(index, new PlatformApi.SessionStatus())! as PlatformApi.SessionStatus;
    default: return null;
  }
}
}

/**
 * @constructor
 */
export namespace PlatformApi{
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Message
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getRoot(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getSizePrefixedRoot(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @returns boolean
 */
static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('RMP1');
};

/**
 * @returns flatbuffers.Long
 */
tts():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns PlatformApi.Body
 */
bodyType():PlatformApi.Body {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : PlatformApi.Body.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
body<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long tts
 */
static addTts(builder:flatbuffers.Builder, tts:flatbuffers.Long) {
  builder.addFieldInt64(0, tts, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param PlatformApi.Body bodyType
 */
static addBodyType(builder:flatbuffers.Builder, bodyType:PlatformApi.Body) {
  builder.addFieldInt8(1, bodyType, PlatformApi.Body.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset bodyOffset
 */
static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, bodyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'RMP1');
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'RMP1', true);
};

static create(builder:flatbuffers.Builder, tts:flatbuffers.Long, bodyType:PlatformApi.Body, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.start(builder);
  Message.addTts(builder, tts);
  Message.addBodyType(builder, bodyType);
  Message.addBody(builder, bodyOffset);
  return Message.end(builder);
}
}
}
