// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.papi;

public final class FeedType {
  private FeedType() { }
  public static final short Default = 0;
  public static final short Trade = 1;

  public static final String[] names = { "Default", "Trade", };

  public static String name(int e) { return names[e]; }
}

