// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.papi;

public final class Side {
  private Side() { }
  public static final byte Sell = -1;
  public static final byte None = 0;
  public static final byte Buy = 1;

  public static final String[] names = { "Sell", "None", "Buy", };

  public static String name(int e) { return names[e - Sell]; }
}

