// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.papi;

public final class SubReqType {
  private SubReqType() { }
  public static final byte Subscribe = 1;
  public static final byte Unsubscribe = 2;

  public static final String[] names = { "Subscribe", "Unsubscribe", };

  public static String name(int e) { return names[e - Subscribe]; }
}

