// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReactiveMarkets.PlatformApi
{

public enum Body : byte
{
  NONE = 0,
  FeedRequest = 1,
  FeedRequestAccept = 2,
  FeedRequestReject = 3,
  LiquidationOrder = 4,
  MDSnapshotL2 = 5,
  PublicTrade = 6,
  SessionStatus = 7,
};


}
