// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReactiveMarkets.PlatformApi
{

public enum Body : byte
{
  NONE = 0,
  FeedRequest = 1,
  FeedRequestAccept = 2,
  FeedRequestReject = 3,
  MDSnapshotL2 = 4,
  PublicTrade = 5,
  SessionStatus = 6,
};


}
