// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReactiveMarkets.PlatformApi
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MDLevel2 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public MDLevel2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Qty { get { return __p.bb.GetDouble(__p.bb_pos + 0); } }
  public double Price { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }

  public static Offset<ReactiveMarkets.PlatformApi.MDLevel2> CreateMDLevel2(FlatBufferBuilder builder, double Qty, double Price) {
    builder.Prep(8, 16);
    builder.PutDouble(Price);
    builder.PutDouble(Qty);
    return new Offset<ReactiveMarkets.PlatformApi.MDLevel2>(builder.Offset);
  }
};


}
