// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package papi

import "strconv"

type FeedType int16

const (
	FeedTypeDefault     FeedType = 0
	FeedTypeTrade       FeedType = 1
	FeedTypeLiquidation FeedType = 2
)

var EnumNamesFeedType = map[FeedType]string{
	FeedTypeDefault:     "Default",
	FeedTypeTrade:       "Trade",
	FeedTypeLiquidation: "Liquidation",
}

var EnumValuesFeedType = map[string]FeedType{
	"Default":     FeedTypeDefault,
	"Trade":       FeedTypeTrade,
	"Liquidation": FeedTypeLiquidation,
}

func (v FeedType) String() string {
	if s, ok := EnumNamesFeedType[v]; ok {
		return s
	}
	return "FeedType(" + strconv.FormatInt(int64(v), 10) + ")"
}
