// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package papi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LiquidationOrder struct {
	_tab flatbuffers.Table
}

func GetRootAsLiquidationOrder(buf []byte, offset flatbuffers.UOffsetT) *LiquidationOrder {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LiquidationOrder{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LiquidationOrder) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LiquidationOrder) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LiquidationOrder) SourceTs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LiquidationOrder) MutateSourceTs(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *LiquidationOrder) Source() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LiquidationOrder) Market() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LiquidationOrder) OrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LiquidationOrder) Flags() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LiquidationOrder) MutateFlags(n uint16) bool {
	return rcv._tab.MutateUint16Slot(12, n)
}

func (rcv *LiquidationOrder) Side() Side {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return Side(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LiquidationOrder) MutateSide(n Side) bool {
	return rcv._tab.MutateInt8Slot(14, int8(n))
}

func (rcv *LiquidationOrder) Qty() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LiquidationOrder) MutateQty(n float64) bool {
	return rcv._tab.MutateFloat64Slot(16, n)
}

func (rcv *LiquidationOrder) Price() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LiquidationOrder) MutatePrice(n float64) bool {
	return rcv._tab.MutateFloat64Slot(18, n)
}

func LiquidationOrderStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func LiquidationOrderAddSourceTs(builder *flatbuffers.Builder, sourceTs int64) {
	builder.PrependInt64Slot(0, sourceTs, 0)
}
func LiquidationOrderAddSource(builder *flatbuffers.Builder, source flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(source), 0)
}
func LiquidationOrderAddMarket(builder *flatbuffers.Builder, market flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(market), 0)
}
func LiquidationOrderAddOrderId(builder *flatbuffers.Builder, orderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(orderId), 0)
}
func LiquidationOrderAddFlags(builder *flatbuffers.Builder, flags uint16) {
	builder.PrependUint16Slot(4, flags, 0)
}
func LiquidationOrderAddSide(builder *flatbuffers.Builder, side Side) {
	builder.PrependInt8Slot(5, int8(side), 0)
}
func LiquidationOrderAddQty(builder *flatbuffers.Builder, qty float64) {
	builder.PrependFloat64Slot(6, qty, 0.0)
}
func LiquidationOrderAddPrice(builder *flatbuffers.Builder, price float64) {
	builder.PrependFloat64Slot(7, price, 0.0)
}
func LiquidationOrderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
