// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package papi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MDLevel2 struct {
	_tab flatbuffers.Struct
}

func (rcv *MDLevel2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MDLevel2) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MDLevel2) Qty() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MDLevel2) MutateQty(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MDLevel2) Price() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *MDLevel2) MutatePrice(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateMDLevel2(builder *flatbuffers.Builder, qty float64, price float64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependFloat64(price)
	builder.PrependFloat64(qty)
	return builder.Offset()
}
