// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package papi

import "strconv"

type Side int8

const (
	SideSell Side = -1
	SideNone Side = 0
	SideBuy  Side = 1
)

var EnumNamesSide = map[Side]string{
	SideSell: "Sell",
	SideNone: "None",
	SideBuy:  "Buy",
}

var EnumValuesSide = map[string]Side{
	"Sell": SideSell,
	"None": SideNone,
	"Buy":  SideBuy,
}

func (v Side) String() string {
	if s, ok := EnumNamesSide[v]; ok {
		return s
	}
	return "Side(" + strconv.FormatInt(int64(v), 10) + ")"
}
