---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: neomantra/flatbuffers:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential
      - name: Generate code
        run: make
